---
- name: Check file system free space
  hosts: all

  tasks:
  - name: Get disk facts
    win_disk_facts:

  - name: Extract free space
    set_fact:
      free_space: "{{ ansible_facts.disks.partition.volumes.size_remaining }}"

  - name: Convert first system disk into various formats
    debug:
     # msg: '{{ disksize_gb }}'
      msg: 'Free disk size: {{ size_remaining_gb }}'
    vars:
     # disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'
     # disksize_gb: '{{ (disk.size/1000|pow(3))|round|int }} GB'  # returns "240 GB" (value in GB)
      size_remaining_gb: '{{ (free_space/1000|pow(3))|round|int }} GB'